name: outputs

on: workflow_dispatch

jobs:
  gen-msg:
    runs-on: ubuntu-latest
    outputs: 
      message: ${{steps.set-message.outputs.greeting1}}
      sample: ${{steps.set-message.outputs.greeting2}}
    steps:
      - id: set-message
        run: 
          echo "greeting1= Hello Welcome" >> $GITHUB_OUTPUT
          echo "greeting2= Simply Hi " >> $GITHUB_OUTPUT

  dis-msg:
    needs: gen-msg
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{needs.gen-msg.outputs.message}}'
      - run: echo '${{needs.gen-msg.outputs.sample}}'
