name: pull_request_edited Workflow


on: 
  pull_request:
     types: edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo 'build'

  test:
    runs-on: windows-latest
    steps:
      - name: Print test - chrome
        run: echo 'test' chrome
      - name: Print test - edge
        run: echo 'test' edge

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy
        run: echo 'deploy'
